
steps:

  - checkout: self
    submodules: recursive
    lfs: true
    path: ./deploy




  - script: |
        git lfs install
        git lfs pull
        git submodule update --init
    displayName: git-deps

  - script: |
        cd ./deploy
        # use absolute paths:
        project_root=$(readlink -f $(dirname ${BASH_SOURCE[0]}))
        $project_root/conda/install_conda.sh
    displayName: build-conda






        # - script: |
        #       cd ./deploy
        #       ./install_all.sh
        #   displayName: build
