stages:
- stage: setup
  jobs:
  - job: checkout
    steps:
    - checkout: self
      submodules: recursive
      lfs: true
      path: ./repo
    - script: |
        git lfs install
        git lfs pull
        git submodule update --init
      displayName: git-deps
    - publish: $(System.DefaultWorkingDirectory)/repo/deploy
      artifact: DeployApp
  - job: apt
    steps:
    - script: |
        sudo apt install -y mpich
    displayName: apt-install
  - job: validate
    dependsOn:
    - checkout
    - apt
    steps:
    - script: |
        ls deploy
        which mpicc
    displayName: validated
- stage: build
  jobs:
  - job: install_all
    steps:
    - script: |
        cd deploy
        ls
        ./install_all.sh
    displayName: build
