stages:
- stage: setup
  jobs:
  - job: checkout
    steps:
    - checkout: self
      submodules: recursive
      lfs: true
      path: ./repo
    - script: |
        git lfs install
        git lfs pull
        git submodule update --init
    displayName: git-deps
  - job: apt
    steps:
    - script: |
        sudo apt install -y mpich
    displayName: apt-install
- stage: build
  jobs:
  - job: install_all
    steps:
    - script: |
        cd deploy
        ls
        ./install_all.sh
    displayName: build
