stages:

- stage: setup
  jobs:
  - job: checkout
    steps:
    - checkout: self
      submodules: recursive
      lfs: true
      path: ./repo
    - script: |
        git lfs install
        git lfs pull
        git submodule update --init
      displayName: git-deps
    - script: |
        tar cvf deploy.tar deploy
      displayName: tar-deploy
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(System.DefaultWorkingDirectory)/deploy.tar"
        ArtifactName: Deploy

- stage: build
  jobs:
  - job: install_all
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: Deploy
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        ls
        tar xvf deploy.tar
      displayName: untar-deploy
    - script: |
        sudo apt install -y mpich
      displayName: apt-install
    - script: |
        cd deploy
        ./install_all.sh
      displayName: build
    - script: |
        tar cvf deploy.tar deploy
      displayName: tar-deploy
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(System.DefaultWorkingDirectory)/deploy.tar"
        ArtifactName: Build
  dependsOn: setup
  condition: succeeded()
